services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:29.0.4
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=$NEXTCLOUD_DB_NAME
      - POSTGRES_USER=$NEXTCLOUD_DB_USER
      - POSTGRES_PASSWORD=$NEXTCLOUD_DB_PASSWORD
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_USER
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_TRUSTED_DOMAINS
    ports:
      - '5010:80'
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - nextcloud-db

  nextcloud-db:
    container_name: nextcloud-db
    image: postgres:16.3
    environment:
      - POSTGRES_DB=$NEXTCLOUD_DB_NAME
      - POSTGRES_USER=$NEXTCLOUD_DB_USER
      - POSTGRES_PASSWORD=$NEXTCLOUD_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - nextcloud-db:/var/lib/postgresql/data

volumes:
  nextcloud: {}
  nextcloud-db: {}
