---
- name: Create NixOS configuration file
  template:
    src: "configuration.nix.j2"
    dest: "/etc/nixos/configuration.nix"
    mode: 0744
  register: config

- name: Rebuild NixOS
  command: "nixos-rebuild switch"
  when: config is changed

- name: "Set ansible_port to {{ SSH_PORT }}"
  set_fact:
    ansible_port: "{{ SSH_PORT }}"
